;;; !!! This configuration is handled by HelloImGui and stores several Ini Files, separated by markers like this:
           ;;;<<<INI_NAME>>>;;;

;;;<<<ImGui_655921752_Default>>>;;;
[Window][WindowOverViewport_11111111]
Pos=0,24
Size=1200,776
Collapsed=0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Beads: beadle##beads-beadle]
Pos=30,40
Size=888,570
Collapsed=0

[Window][world_panel]
Pos=639,110
Size=97,150
Collapsed=0

[Table][0x351C188B,5]

[Docking][Data]
DockSpace ID=0x08BD597D Window=0x1BBC0F80 Pos=0,24 Size=1200,776 CentralNode=1

;;;<<<Layout_655921752_Default>>>;;;
;;;<<<HelloImGui_Misc>>>;;;
[Layout]
Name=Default
[Theme]
Name=DarculaDarker
;;;<<<SplitIds>>>;;;
{"gImGuiSplitIDs":{}}
